version: '3'
services:

    mongo_1:
        image: idragan/mongo1:imported
        command: mongod --port 27017 --dbpath /data/db1
        hostname: mongo_1
        expose:
            - 27017
        ports:
            - "27017:27017"
             
             
              #   mongo_2:
              #        command: mongod --port 27018
              #        hostname: mongo_2
              #        expose:
              #            - 27018
              #        ports:
              #            - "27018:27018"

    mongo_2:
        image: idragan/mongo2:imported
        command: mongod --port 27018 --dbpath /data/db1
        hostname: mongo_2
        expose:
            - 27018
        ports:
            - "27018:27018"


    rserver:
            #image: obiba/opal-rserver:latest
        image: idragan/rserver:latest
        hostname: rserver
        environment:
            - RSERVER_HOME=/srv_local
            - JAVA_OPTS=-Xms512m -Xmx2G -XX:+UseG1GC

    opal_server1:
        image: idragan/opalsrv:latest
        hostname: opal_server1
        expose:
            - 8443
            - 8080
        ports:
            - "8843:8443"
            - "8880:8080"
            # Ports convention: <port on host>:<port inside container>
        links:
            - rserver
            - mongo_1
        environment:
            - JAVA_OPTS=-Xms32m -Xmx512m -XX:+UseG1GC
            - OPAL_ADMINISTRATOR_PASSWORD=password
              #           - OPAL_HOME=/srv_local
            - RSERVER_HOST=rserver  
            - MONGO_HOST=mongo_1
            - MONGO_PORT=27017
            - DRIVING_SITE="TRUE"
                
        #volumes:
        #    - /tmp/opal_server_1:/srv

    opal_server2:
        image: idragan/opalsrv:latest
        hostname: opal_server2
        expose:
            - 8443
            - 8080
        ports:
            - "9843:8443"
            - "9880:8080"
        links:
            - rserver
            - mongo_2
        depends_on:
            - opal_server1    
        environment:
            - JAVA_OPTS=-Xms32m -Xmx512m -XX:+UseG1GC
            - OPAL_ADMINISTRATOR_PASSWORD=password
              #            - OPAL_HOME=/srv_local
            - RSERVER_HOST=rserver  
            - MONGO_HOST=mongo_2
            - MONGO_PORT=27018

              #    rstudio_client:
              #        image: idragan/rstudio_client:imported
              #        hostname: rstudio_client
              #        expose:
              #            - 8787
              #        ports:
              #            - "8787:8787"
              #            # Ports convention: <port on host>:<port inside container>
              #        links:
              #            - opal_server1
              #            - opal_server2
              #        environment:
              #            - ROOT=TRUE
              #            - DISABLE_AUTH=TRUE

